(source gnu)
(source melpa)

(depends-on "smooth-scroll")
(depends-on "markdown-mode")
(depends-on "flycheck-pos-tip")
(depends-on "flycheck")
(depends-on "darcula-theme")
(depends-on "init-loader")
(depends-on "auto-complete")
(depends-on "popup")
(depends-on "helm")
(depends-on "smartparens")
(depends-on "rainbow-delimiters")
(depends-on "cl-lib")
(depends-on "color")
(depends-on "ace-jump-mode")