(source gnu)
(source melpa)
(source marmalade)

(depends-on "ace-jump-mode")
(depends-on "yasnippet")
(depends-on "darcula-theme")
(depends-on "smart-mode-line")
(depends-on "migemo")
(depends-on "quickrun")
(depends-on "ace-isearch")
(depends-on "cl-lib")
(depends-on "git-gutter+")
(depends-on "rainbow-delimiters")
(depends-on "smartparens")
(depends-on "recentf-ext")
(depends-on "color")
(depends-on "smart-newline")
(depends-on "undo-tree")
(depends-on "fuzzy")
(depends-on "direx")
(depends-on "pallet")
(depends-on "init-loader")
(depends-on "use-package")
(depends-on "bind-key")
(depends-on "jedi")
(depends-on "popwin")
(depends-on "magit")

;; flycheck
(depends-on "flycheck")
(depends-on "pos-tip")
(depends-on "flycheck-tip")
;; (depends-on "flycheck-pos-tip")

;; select region
(depends-on "multiple-cursors")
(depends-on "expand-region")
(depends-on "smartrep")

;; helm
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "helm-flycheck")
(depends-on "helm-gtags")
(depends-on "helm-descbinds")
(depends-on "helm-bind-key")
(depends-on "helm-pydoc")

;; auto-complete
(depends-on "auto-complete")
(depends-on "auto-complete-c-headers")
(depends-on "auto-complete-clang")
(depends-on "auto-complete-clang-async")
(depends-on "ac-emmet")
(depends-on "ac-js2")
(depends-on "popup")

;; major/minor mode
(depends-on "swift-mode")
(depends-on "markdown-mode")
(depends-on "php-mode")
(depends-on "web-mode")
(depends-on "matlab-mode")
(depends-on "emmet-mode")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "skewer-mode")
(depends-on "typescript-mode")
(depends-on "tide")
(depends-on "company")