(source gnu)
(source melpa)

(depends-on "ac-slime" :git "https://github.com/purcell/ac-slime")
(depends-on "ace-jump-mode")
(depends-on "auto-complete")
(depends-on "cl-lib")
(depends-on "color")
(depends-on "darcula-theme")
(depends-on "flycheck")
(depends-on "flycheck-pos-tip")
(depends-on "helm")
(depends-on "init-loader")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "popup")
(depends-on "popwin" :git "https://github.com/m2ym/popwin-el")
(depends-on "rainbow-delimiters")
(depends-on "slime" :git "https://github.com/slime/slime")
(depends-on "smartparens")
(depends-on "smooth-scroll")
